name: internetbanking
description: An internet banking balance simulator

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Theme & icons & animations
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.17.4
  lottie: ^0.7.0+1
  # Stage management
  flutter_bloc: ^6.1.2
  # Local cache
  flutter_secure_storage: ^3.3.3
  # Others
  intl: ^0.16.1

dev_dependencies:
  # Analysis
  pedantic: ^1.8.0
  # Tests
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700